menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: xavier_seignard
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: true

google_analytics: UA-37483328-1
rss: